insert into public.profile (id, full_name, headline, bio, location, email, phone, hero_image_url, years_experience, projects_completed, teams_coordinated)
values ('00000000-0000-0000-0000-000000000001', 'CIVORA INFRASTRUCTURE', 'Civil Engineering and Infrastructure Development Company', 'CIVORA INFRASTRUCTURE is a construction and civil engineering company focused on disciplined site execution, infrastructure coordination, quality control, and practical delivery systems for complex built environments.', 'Pakistan', 'projects@example.com', '+92 300 0000000', 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1600&q=80', 7, 18, 6)
on conflict (id) do update set full_name = excluded.full_name;

insert into public.projects (title, slug, category, location, year, status, client_type, short_description, full_description, scope, challenges, solution, result, cover_image_url, gallery_urls, metrics, is_featured, is_published) values
('Residential Grey Structure Coordination','residential-grey-structure-coordination','Residential','Lahore',2024,'Completed','Private homeowner','Site coordination for foundations, columns, slabs, masonry, and finishing handover planning.','Private residence requiring steady supervision across structural work and early finishing coordination.','Daily site checks, contractor coordination, concrete pour readiness, material follow-up, and progress reporting.','Maintaining work continuity while aligning trades, deliveries, and consultant observations.','Weekly look-ahead planning, clearer work fronts, and practical inspection checklist before major activities.','Improved sequence control, fewer rework items, and cleaner transition from structure to finishing.','https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=1600&q=80', array['https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1600&q=80'], '{"Scope":"Grey structure","Duration":"8 months","Teams":"4 site teams"}', true, true),
('Commercial Plaza Fit-Out Support','commercial-plaza-fit-out-support','Commercial','Islamabad',2023,'Completed','Commercial developer','Coordination of partitioning, ceiling, MEP follow-ups, finishing snag lists, and vendor access.','Commercial fit-out phase where multiple vendors needed access without blocking finishing progress.','Fit-out sequencing, quality inspections, site meetings, punch lists, and vendor coordination.','Concurrent ceiling, electrical, HVAC, and finishing teams competing for limited work zones.','Zone-based scheduling and daily access windows for critical vendors.','Clearer handover tracking and faster closure of finishing defects.','https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1600&q=80', array['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1600&q=80'], '{"Zones":"5 floors","Focus":"Fit-out","Vendors":"9 vendors"}', true, true),
('Warehouse Slab and Utilities Package','warehouse-slab-utilities-package','Industrial','Karachi',2022,'Completed','Industrial operator','Industrial slab preparation, utility trench coordination, and pre-pour inspection support.','Warehouse improvement package focused on durable slab work and utility coordination.','Subgrade checks, reinforcement observations, pour planning, curing follow-up, and utility sleeve coordination.','Heavy-use floor requirements and tight access for concrete placement.','Pre-pour checklists, access planning, and close coordination with the batching supplier.','A more controlled pour sequence and documented quality checkpoints.','https://images.unsplash.com/photo-1531834685032-c34bf0d84c77?auto=format&fit=crop&w=1600&q=80', array['https://images.unsplash.com/photo-1590479773265-7464e5d48118?auto=format&fit=crop&w=1600&q=80'], '{"Area":"42,000 sq ft","Package":"Slab and utilities","Checks":"Pre-pour QA"}', false, true),
('Roadside Drainage and Civil Works','roadside-drainage-civil-works','Infrastructure','Faisalabad',2021,'Completed','Local contractor','Drainage channels, concrete works, level checks, and field coordination for public-facing works.','Focused civil works package requiring coordination around traffic, safety, and levels.','Setting-out support, formwork checks, concrete coordination, and site safety observations.','Live surroundings and the need to keep access open during works.','Segmented execution, barricading, and short daily coordination meetings.','Progress remained organized while maintaining cleaner public access.','https://images.unsplash.com/photo-1565008447742-97f6f38c985c?auto=format&fit=crop&w=1600&q=80', array['https://images.unsplash.com/photo-1517089596392-fb9a9033e05b?auto=format&fit=crop&w=1600&q=80'], '{"Length":"1.2 km","Work":"Drainage","Safety":"Live-site controls"}', false, true),
('Apartment Renovation Coordination','apartment-renovation-coordination','Renovation','Rawalpindi',2024,'In Progress','Private client','Renovation sequencing for demolition, plumbing, electrical rough-in, finishes, and handover checks.','Controlled apartment renovation focused on quality, communication, and limited disruption.','Work sequencing, contractor follow-up, material coordination, and defect tracking.','Occupied-building restrictions and limited working hours.','Noise-aware scheduling, advance material staging, and compact daily progress reporting.','Better client visibility and reduced idle time between trades.','https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80', array['https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1600&q=80'], '{"Units":"1 apartment","Trades":"6 trades","Status":"Active"}', true, true),
('Villa Finishing and Handover Controls','villa-finishing-handover-controls','Residential','Multan',2023,'Completed','Private client','Finishing quality checks, snag lists, vendor coordination, and final handover documentation.','Residential finishing stage requiring disciplined tracking of paint, tile, joinery, and MEP defects.','Snag list management, finishing inspections, vendor coordination, and owner reporting.','Finishing details needed consistent closure before handover.','Room-by-room handover sheets and direct issue ownership for each trade.','A more transparent completion path and fewer unresolved handover items.','https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1600&q=80', array['https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=1600&q=80'], '{"Rooms":"12 spaces","Focus":"Finishing","Handover":"Snag tracking"}', false, true)
on conflict (slug) do nothing;

insert into public.services (title, slug, icon, short_description, includes, outcome, sort_order, is_published) values
('Construction Project Management','construction-project-management','ClipboardCheck','Planning, sequencing, progress tracking, and issue follow-up for construction delivery.',array['Look-ahead schedules','Progress reviews','Stakeholder coordination'],'A clearer path from drawings to site execution.',1,true),
('Site Supervision','site-supervision','HardHat','Daily site oversight with practical quality, safety, and productivity checks.',array['Daily inspections','Work-front coordination','Site reporting'],'Better control over workmanship and activity flow.',2,true),
('Civil Works Coordination','civil-works-coordination','Landmark','Coordination for foundations, concrete, masonry, drainage, and site preparation works.',array['Setting-out support','Concrete readiness','Civil team follow-up'],'Civil packages that move with fewer avoidable delays.',3,true),
('Residential and Commercial Construction','residential-commercial-construction','Building2','Execution support for homes, plazas, offices, and mixed-use construction projects.',array['Structure coordination','Finishing follow-up','Client updates'],'Organized delivery across structure and finishing phases.',4,true),
('Renovation and Fit-Out Coordination','renovation-fit-out-coordination','PaintRoller','Trade sequencing and finishing controls for occupied or fast-moving renovation sites.',array['Demolition planning','MEP coordination','Snag lists'],'Cleaner fit-out execution and smoother handover.',5,true),
('Quality and Safety Monitoring','quality-safety-monitoring','ShieldCheck','Practical checklists and site observations to support workmanship and safer operations.',array['Inspection sheets','Safety walks','Corrective action tracking'],'Fewer surprises during consultant and client reviews.',6,true),
('BOQ and Material Coordination','boq-material-coordination','Boxes','Support for BOQ understanding, material planning, purchase follow-up, and wastage awareness.',array['Quantity review','Material logs','Delivery coordination'],'Better alignment between planned work and available materials.',7,true),
('Contractor and Vendor Management','contractor-vendor-management','UsersRound','Coordination between contractors, vendors, consultants, and client representatives.',array['Meeting notes','Responsibility tracking','Vendor access planning'],'Less confusion and stronger accountability on site.',8,true)
on conflict (slug) do nothing;

insert into public.testimonials (person_name, person_role, company, message, rating, is_published) values
('Project Owner','Client representative','Residential Project','The site conversations stayed focused and practical. Progress reporting was clear, and issues were easier to close.',5,true),
('Site Engineer','Consultant team','Commercial Works','The strongest value was coordination between trades. We had fewer surprises when finishing activities overlapped.',5,true),
('Fit-Out Contractor','Contractor','Interior Package','His site follow-up helped us keep quality observations visible without slowing every work front.',4,true),
('Civil Supervisor','Civil works lead','Civil Package','Communication with contractors and suppliers became more organized during the concrete and masonry stages.',5,true),
('Private Client','Homeowner','Renovation Project','For renovation work, the daily sequencing and snag tracking made the handover process much smoother.',5,true),
('Development Coordinator','Project stakeholder','Mixed-Use Site','A reliable construction professional for practical site execution and stakeholder updates.',5,true);

insert into public.gallery (title, category, image_url, description, sort_order, is_published) values
('Site Progress','Site Progress','https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=1600&q=80','Construction documentation image for site progress, civil works, and field coordination context.',1,true),
('Concrete Activity','Civil Works','https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1600&q=80','Construction documentation image for site progress, civil works, and field coordination context.',2,true),
('Structural Frame','Structural Work','https://images.unsplash.com/photo-1531834685032-c34bf0d84c77?auto=format&fit=crop&w=1600&q=80','Construction documentation image for site progress, civil works, and field coordination context.',3,true),
('Drainage Works','Civil Works','https://images.unsplash.com/photo-1565008447742-97f6f38c985c?auto=format&fit=crop&w=1600&q=80','Construction documentation image for site progress, civil works, and field coordination context.',4,true),
('Equipment Coordination','Equipment','https://images.unsplash.com/photo-1581094288338-2314dddb7ece?auto=format&fit=crop&w=1600&q=80','Construction documentation image for site progress, civil works, and field coordination context.',5,true),
('Facade Review','Finishing','https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=1600&q=80','Construction documentation image for site progress, civil works, and field coordination context.',6,true),
('Interior Planning','Team Coordination','https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80','Construction documentation image for site progress, civil works, and field coordination context.',7,true),
('Finishing Work','Finishing','https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1600&q=80','Construction documentation image for site progress, civil works, and field coordination context.',8,true),
('MEP Coordination','Team Coordination','https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=80','Construction documentation image for site progress, civil works, and field coordination context.',9,true),
('Final Checks','Finishing','https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=1600&q=80','Construction documentation image for site progress, civil works, and field coordination context.',10,true),
('Residential Exterior','Structural Work','https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1600&q=80','Construction documentation image for site progress, civil works, and field coordination context.',11,true),
('Site Inspection','Site Progress','https://images.unsplash.com/photo-1485083269755-a7b559a4fe5e?auto=format&fit=crop&w=1600&q=80','Construction documentation image for site progress, civil works, and field coordination context.',12,true);

insert into public.site_settings (key, value) values
('seo', '{"siteName":"CIVORA INFRASTRUCTURE","tagline":"Civil Engineering and Infrastructure Development Company"}'),
('theme', '{"primary":"deep navy","accent":"safety yellow","style":"premium construction company website"}')
on conflict (key) do update set value = excluded.value;
